version: "3.7"

services:
  redis:
    image: redis

  unifiedpost:

    build:
      context: ../
      dockerfile: ./docker/dev.Dockerfile

    environment:
      - ENV

    depends_on:
      - redis

    ports:
    - 8080:8080
